import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AdminNavbar from "./components/Navbar";
import Footer from "./components/Footer";
import { EdgeStoreProvider } from "./lib/edgestore";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Eco-Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AdminNavbar />
        <EdgeStoreProvider>
            {children}
        </EdgeStoreProvider>
      
        <Footer />
      </body>
    </html>
  );
}
